import { Fab } from "@mui/material";

export const form = {
    "id": 1,
    "name": "Form #1",
    "fieldsets": [
        {
            "name": "patient_registration_form",
            "legend_text": "Patient Registration Form",
            "inputs": [
                {
                    "name": "full_name",
                    "label_text": "Full Name",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "nickname",
                    "label_text": "Nickname",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "dob",
                    "label_text": "DOB",
                    "required": true,
                    "type": "date"
                },
                {
                    "name": "age",
                    "label_text": "Age",
                    "required": true,
                    "type": "number",
                },
                {
                    "name": "address",
                    "label_text": "Address",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "city",
                    "label_text": "City",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "state",
                    "label_text": "State",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "zip",
                    "label_text": "ZIP",
                    "required": true,
                    "type": "number",
                },
                {
                    "name": "physical_address",
                    "label_text": "Physical Address(if different)",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "hm_phone",
                    "label_text": "HM Phone",
                    "required": true,
                    "type": "tel",
                },
                {
                    "name": "cell_phone",
                    "label_text": "Cell Phone",
                    "required": true,
                    "type": "tel",
                },
                {
                    "name": "work_phone",
                    "label_text": "Work Phone",
                    "required": true,
                    "type": "tel",
                },
                {
                    "name": "social_security_number",
                    "label_text": "SS#",
                    "required": true,
                    "type": "number",
                },
                {
                    "name": "mariage_statis",
                    "label_text": "Single",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "mariage_statis",
                    "label_text": "Married",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "mariage_statis",
                    "label_text": "Divorced",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "mariage_statis",
                    "label_text": "Widowed",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "mariage_statis",
                    "label_text": "Student",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "employed_by",
                    "label_text": "Employed By",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "occupation",
                    "label_text": "Occupation",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "spouse_name",
                    "label_text": "Spouse Name",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "spouse_social_security_number",
                    "label_text": "SS#",
                    "required": true,
                    "type": "number",
                },
                {
                    "name": "email_address",
                    "label_text": "Email Address",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "spouse_address",
                    "label_text": "Address",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "years_held",
                    "label_text": "Years Held",
                    "required": true,
                    "type": "number",
                },
                {
                    "name": "spouse_employer",
                    "label_text": "Spouse Employer",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "spouse_work_phone",
                    "label_text": "Spouse Work Phone",
                    "required": true,
                    "type": "tel",
                },
            ]
        },
        {
            "name": "who_is_responsible_for_account",
            "legend_text": "Who Is Responsible For Account?",
            "inputs": [
                {
                    "name": "name",
                    "label_text": "Name",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "date_of_birth",
                    "label_text": "Date of Birth",
                    "required": true,
                    "type": "date",
                },
                {
                    "name": "relationship_to_patient",
                    "label_text": "Relationship To Patient",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "responsible_address",
                    "label_text": "Address",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "phone",
                    "label_text": "Phone",
                    "required": true,
                    "type": "tel",
                },
                {
                    "name": "responsible_social_security_number",
                    "label_text": "SS#",
                    "required": true,
                    "type": "number",
                },
                {
                    "name": "medicare",
                    "label_text": "Do You Have Medicare?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "medicare_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "medicare_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "medicaid",
                    "label_text": "Medicaid?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "medicaid_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "medicaid_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
            ]
        },
        {
            "name": "dental_insurance",
            "legend_text": "Dental Insurance",
            "inputs": [
                {
                    "name": "insurance_company",
                    "label_text": "Insurance Company",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "insureds_name",
                    "label_text": "Insured's Name",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "insureds_employer_or_individual_holding_insurance",
                    "label_text": "Insured's Employer Or Individual Holing Insurance",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "insureds_social_security_number",
                    "label_text": "Insured's SS#",
                    "required": true,
                    "type": "number",
                },
                {
                    "name": "insureds_date_of_birth",
                    "label_text": "Date of Birth",
                    "required": true,
                    "type": "date",
                },
                {
                    "name": "group_number",
                    "label_text": "Group #",
                    "required": true,
                    "type": "number",
                },
            ]
        },
        {
            "name": "secondary_dental_or_medical_insurance",
            "legend_text": "Secondary Dental Or Medical(If Applicable) Insurance",
            "inputs": [
                {
                    "name": "insurance_co",
                    "label_text": "Insurance Co.",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "secondary_insureds_name",
                    "label_text": "Insured's Name",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "secondary_insureds_employer_or_individual_holding_insurance",
                    "label_text": "Insured's Employer Or Individual Holing Insurance",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "secondary_insureds_social_security_number",
                    "label_text": "Insured's SS#",
                    "required": true,
                    "type": "number",
                },
                {
                    "name": "secondary_insureds_date_of_birth",
                    "label_text": "Date of Birth",
                    "required": true,
                    "type": "date",
                },
                {
                    "name": "secondary_group_number",
                    "label_text": "Group #",
                    "required": true,
                    "type": "number",
                },
            ]
        },
        {
            "name": "parent_information",
            "legend_text": "Parent Information(If Patient Is A Minor Or Student)",
            "inputs": [
                {
                    "name": "mothers_name",
                    "label_text": "Mother's Name",
                    "requried": false,
                    "type": "text",
                },
                {
                    "name": "mothers_social_security_number",
                    "label_text": "SS#",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "mothers_address",
                    "label_text": "Mother's Address",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "mothers_homecell_phone",
                    "label_text": "Home/Cell Phone",
                    "required": false,
                    "type": "tel",
                },
                {
                    "name": "mothers_employer",
                    "label_text": "Mother's Employer",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "mothers_work_phone",
                    "label_text": "Work Phone",
                    "required": false,
                    "type": "tel",
                },
                {
                    "name": "fathers_name",
                    "label_text": "Father's Name",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "fathers_social_security_number",
                    "label_text": "SS#",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "fathers_address",
                    "label_text": "Father's Address",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "fathers_homecell_phone",
                    "label_text": "Home/Cell Phone",
                    "required": false,
                    "type": "tel",
                },
                {
                    "name": "fathers_employer",
                    "label_text": "Father's Employer",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "fathers_work_phone",
                    "label_text": "Work Phone",
                    "required": false,
                    "type": "tel",
                },
            ]
        },
        {
            "name": "other",
            "legend_text": "Other",
            "inputs": [
                {
                    "name": "referred",
                    "label_text": "I Was Referred To Dr. Griffitts by:",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "emergency_contact_name",
                    "label_text": "Emergency Contact Name",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "phone_number",
                    "label_text": "Phone #",
                    "required": true,
                    "type": "tel",
                },
                {
                    "name": "relationship",
                    "label_text": "Relationship",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "payment_type",
                    "label_text": "I Will Be Paying Today By:",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "payment",
                    "label_text": "Cash",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "payment",
                    "label_text": "Check",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "payment",
                    "label_text": "Credit Card",
                    "required": false,
                    "type": "radio",
                },
                // signiture here
            ]
        },
        {
            "name": "medical_history",
            "legend_text": "Medical History",
            "inputs": [
                {
                    "name": "mh_name",
                    "label_text": "Name",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "mh_date_of_birth",
                    "label_text": "Date Of Birth",
                    "required": true,
                    "type": "date",
                },
                {
                    "name": "height",
                    "label_text": "Height",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "weight",
                    "label_text": "Weight",
                    "required": true,
                    "type": "text",
                },
                {
                    "name": "sex",
                    "label_text": "Sex",
                    "required": true,
                    "type": "text",
                },
                // question infomaiton here
                {
                    "name": "have_you_ever_been_hostpitalized",
                    "label_text": "Have You Ever Been Hostipitalized?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "hospitalized",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "hospitalized",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "if_yes_what_for",
                    "label_text": "If Yes, What For",
                    "requried": false,
                    "type": "text",
                },
                {
                    "name": "have_you_been_under_the_care_of_a_medical_doctor",
                    "label_text": "Have You Been Under The Care Of A Medical Doctor?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "medical_doctor",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "medical_doctor",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "if_yes_who_and_what_for",
                    "label_text": "If Yes, Who And What For",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "are_you_taking_any_medications",
                    "label_text": "Are You Taking Any Medications?",
                    "requried": false,
                    "type": "hidden",
                },
                {
                    "name": "medications",
                    "label_text": "Yes",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "medications",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "if_yes_please_list",
                    "label_text": "If Yes, Please List",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "do_you_have_allergies_to_food_or_medication",
                    "label_text": "Do You Have Allergies To Food Or Medication?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "allergies",
                    "label_text": "Yes",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "allergies",
                    "label_text": "No",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "if_yes_please_list_allergies",
                    "label_text": "If Yes, Please List",
                    "requried": false,
                    "type": "text",
                },
                {
                    "name": "have_you_had_any_previous_surgeries",
                    "label_text": "Have You Had Any Previous Surgeries?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "surgeries",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "surgeries",
                    "label_text": "No",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "if_yes_please_list_surgeries",
                    "label_text": "If Yes, Please List",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "have_you_ever_been_diagnosed_with_mrsa",
                    "label_text": "Have You Ever Been Diagnosed With MRSA?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "mrsa",
                    "label_text": "Yes",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "mrsa",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "genral_anesthesa",
                    "label_text": "Have You Or Any Relatives Had Coplications From General Anesthesa?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "anesthesa",
                    "label_text": "Yes",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "anesthesa",
                    "label_text": "No",
                    "requried": false,
                    "type": "radio",
                },
            ]
        },
        {
            "name": "apply_to_your_medical_history",
            "legend_text": "Check Any Of The Following That Apply To Your Medical History",
            "inputs": [
                {
                    "name": "heart_disease",
                    "label_text": "Heart Disease",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "heartdisease",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "heartdisease",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "heart_attack",
                    "label_text": "Heart Attack",
                    "requried": false,
                    "type": "hidden",
                },
                {
                    "name": "heartattack",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "heartattack",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "heart_murmur",
                    "label_text": "Heart Murmur",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "heartmurmur",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "heartmurmur",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "congenital_heart_disease",
                    "label_text": "Congenital Heart Disease",
                    "requried": false,
                    "type": "hidden",
                },
                {
                    "name": "congenitalheartdisease",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "congenitalheartdisease",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "artificial_heart_valve",
                    "label_text": "Artificial Heart Valve",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "artificialheartvalve",
                    "label_text": "Yes",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "artificialheartvalve",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "cardiac_pacemaker",
                    "label_text": "Cardiac Pacemake",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "cardiacpacemaker",
                    "label_text": "Yes",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "cardiacpacemaker",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "cardiac_surgery",
                    "label_text": "Cardiac Surgery",
                    "requried": false,
                    "type": "hidden",
                },
                {
                    "name": "cardiacsurgery",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "cardiacsurgery",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "chest_pain",
                    "label_text": "Chest Pain",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "chestpain",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "chestpain",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "high_blood_pressure",
                    "label_text": "High Blood Pressure",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "highbloodpressure",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "highbloodpressure",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "tuberculosis",
                    "label_text": "Tuberculosis",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "tuberculosis_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "tuberculosis_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "asthma",
                    "label_text": "Asthma",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "asthma_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "asthma_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "emphysema",
                    "label_text": "Emphysema",
                    "requried": false,
                    "type": "hidden",
                },
                {
                    "name": "emphysema_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "emphysema_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "stroke",
                    "label_text": "Stroke",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "stroke_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "stroke_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "seizureepilepsy",
                    "label_text": "Seizure/Epilespy",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "seizureepilepsy_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "seizureepilepsy",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "dizzinessfainting",
                    "label_text": "Dizziness/Fainting",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "dizzinessfainting_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "dizzinessfainting_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "anxiety",
                    "label_text": "Anxiety",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "anxiety_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "anxiety_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "psychaitric_treatment",
                    "label_text": "Psychaitric Treatment",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "psychaitrictreatment",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "psychaitrictreatment",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "ulcers",
                    "label_text": "Ulcers",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "ulcers_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "ulcers_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "hepatitisjaundice",
                    "label_text": "Hepatitis/Jaundice",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "hepatitisjaundice_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "hepatitisjaundice_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "diabetes",
                    "label_text": "Diabetes",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "diabetes_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "diabetes_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "thyroid_problems",
                    "label_text": "Thyroid Problems",
                    "required": false, 
                    "type": "hidden",
                },
                {
                    "name": "thyroidproblems",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "thyroidproblems",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "chemotherapy",
                    "label_text": "Chemotherapy",
                    "requried": false,
                    "type": "hidden",
                },
                {
                    "name": "chemotherapy_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "chemotherapy_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "tumor",
                    "label_text": "Tumor",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "tumor_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "tumor_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "cancer",
                    "label_text": "Cancer",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "cancer_radio",
                    "label_text": "Yes",
                    "required": false, 
                    "type": "radio",
                },
                {
                    "name": "cancer_radio",
                    "label_text": "No",
                    "required": false, 
                    "type": "radio",
                },
                {
                    "name": "radiation_treatment",
                    "label_text": "Radiation Treatment",
                    "requried": false,
                    "type": "hidden",
                },
                {
                    "name": "radiationtreatment",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "radiationtreatment",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "steroid_medication",
                    "label_text": "Steroid Medication",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "steroidmedication",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "steroidmedication",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "hivesallergy",
                    "label_text": "Hives/Allergy",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "hivesallergy_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "hivesallergy_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "hay_fever",
                    "label_text": "Hay Fever",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "hayfever",
                    "label_text": "Yes",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "hayfever",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "hemophilla",
                    "label_text": "Hemophilla",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "hemophilla_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "hemophilla",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "sickle_cell_disease",
                    "label_text": "Sickle Cell Disease",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "sicklecelldisease",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "sicklecelldisease",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "anemia",
                    "label_text": "Anemia",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "anemia_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "anemia_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "bruise_easily",
                    "label_text": "Bruise Easlily",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "bruiseeasily",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "bruiseeasily",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "arthritisrheumatism",
                    "label_text": "Arthritis/Rheumatism",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "arthritisrheumatism_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "arthritisrheumatism_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "artificial_joints",
                    "label_text": "Artificial Joints",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "artificialjoints",
                    "label_text": "Yes",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "artificialjoints",
                    "label_text": "No",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "kidney_disease",
                    "label_text": "Kindey Disease",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "kidneydisease",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "kidneydisease",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "venereal_disease",
                    "label_text": "Venereal Disease",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "venerealdisease",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "venerealdisease",
                    "label_text": "No",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "glaucoma",
                    "label_text": "Glaucoma",
                    "requried": false,
                    "type": "hidden",
                },
                {
                    "name": "glaucoma_radio",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "glaucoma_radio",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "sinus_disease",
                    "label_text": "Sinus Disease",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "sinusdisease",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "sinusdisease",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "pain_in_jaw_joints",
                    "label_text": "Pain In Jaw Joints",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "paininjawjoints",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "paininjawjoints",
                    "label_text": "No",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "locking_of_jaw_joints",
                    "label_text": "Locking Of Jaw Joints",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "lockingofjawjoints",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "lockingofjawjoints",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "popping_of_jaw_joints",
                    "label_text": "Popping Of Jaw Joints",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "poppingofjawjoints",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "poppingofjawjoints",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "sleep_apnea",
                    "label_text": "Sleep Apnea",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "sleepapnea",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "sleepapnea",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
            ]
        },
        {
            "name": "medical_history_continued",
            "legend_text": "Medical History Continued",
            "inputs": [
                {
                    "name": "are_you_currently_taking_a_blood_thinner_",
                    "label_text": "Are You Currently Taking A Blood Thinner?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "areyoucurrentlytakingabloodthinner",
                    "label_text": "Yes",
                    "requried": false,
                    "type": "radio",
                },
                {
                    "name": "areyoucurrentlytakingabloodthinner",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "blood_thinner_name",
                    "label_text": "Name:",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "do_you_use_diet_medications",
                    "label_text": "Do You Use Diet Medications?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "doyouusedietmedications",
                    "label_text": "yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "doyouusedietmedications",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "if_so_please_list",
                    "label_text": "If So, Please List",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "have_you_ever_taken",
                    "label_text": "Have You Ever Taken bisphosphonates: Fosamax, Actonel, Boniva?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "haveyouevertaken",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "haveyouevertaken",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "if_so_please_list_taken",
                    "label_text": "If So, Please List",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "do_you_have_any_condition_not_listed_above",
                    "label_text": "Do You Have Any Condition Not Listed Above",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "doyouhaveanyconditionnotlistedabove",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "doyouhaveanyconditionnotlistedabove",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "do_you_currently_smoke_or_have_a_history_of_smoking",
                    "label_text": "Do You Currently Smoke, Or Have A History Of Smoking?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "doyoucurrentlysmokeorhaveahistoryofsmoking",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "doyoucurrentlysmokeorhaveahistoryofsmoking",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "packs",
                    "label_text": "If So, How Many Packs Per Day?",
                    "required": false,
                    "type": "number",
                },
                {
                    "name": "years",
                    "label_text": "How Many Years?",
                    "required": false,
                    "type": "number",
                },
                {
                    "name": "do_you_currently_use_smokeless_tobacco_or_used_to_in_the_past",
                    "label_text": "Do You Currently Use Smokeless Tobacco, Or Used To In The Past?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "doyoucurrentlyusesmokelesstobaccoorusedtointhepast",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "doyoucurrentlyusesmokelesstobaccoorusedtointhepast",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "do_you_drink_any_alcohol",
                    "label_text": "Do You Drink Any Alcohol?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "doyoudrinkanyalcohol",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "doyoudrinkanyalcohol",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "if_so_how_much_and_how_often",
                    "label_text": "If So, How Much And How Often",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "do_you_use_any_recreational_drugs",
                    "label_text": "Do You Use Any Recreational Drugs?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "doyouuseanyrecreationaldrugs",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "doyouuseanyrecreationaldrugs",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "if_so_please_list_drugs",
                    "label_text": "If So, Please List",
                    "required": false,
                    "type": "text",
                },
                {
                    "name": "men",
                    "label_text": "MEN:",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "do_you_use_erectile_dysfunction_medications",
                    "label_text": "Do You Use Erectile Dysfunction Medications?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "doyouuseerectiledysfunctionmedications",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "doyouuseerectiledysfuntionmedications",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "women",
                    "label_text": "WOMEN:",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "are_you_pregnant_or_trying_to_get_pregnant",
                    "label_text": "Are You Pregnant Or Trying To Get Pregnant",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "areyoupregnantortryingtogetpregnant",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "areyoupregnantortryingtogetpregnant",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "are_you_nursing",
                    "label_text": "Are You Nursing?",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "areyounursing",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "areyounursing",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "are_you_using_oral_contraceptives",
                    "label_text": "Are You Using Oral Contraceptives",
                    "required": false,
                    "type": "hidden",
                },
                {
                    "name": "areyouusingoralcontraceptives",
                    "label_text": "Yes",
                    "required": false,
                    "type": "radio",
                },
                {
                    "name": "areyouusingoralcontraceptives",
                    "label_text": "No",
                    "required": false,
                    "type": "radio",
                },
                //signature
            ]
        }
    ]
}